### ISSUE TITLE
Front-End Track Courses to be Completed

### ISSUE THREAD

**Issue by CharlotteJames2020** [CharlotteJames2020/Treehouse#2]
## TODO 

*Courses left to complete the Treehouse Front-End Track*

* [ ] CSS Layout Basics
* [ ] JavaScript Loops, Arrays and Object
* [ ] CSS Selectors
* [ ]  jQuery Basics
* [ ] CSS Flexbox Layout
* [ ] JavaScript and the DOM
* [ ] Responsive Layouts
* [ ] AJAX Basics
* [ ] Bootstrap 4 Basics
* [ ] Accessibility
* [ ] Website Optimization
* [ ] Introduction  to Design Patterns

🎉  🙆  🎊
